version: '3.8'

services:
  app:
    container_name: boo-yah
    image: simple-app
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
